### ISSUE TITLE
ConfigDict does not add global_conf values to overall settings dict

### ISSUE THREAD

**Issue by redbaron4** [Pylons/plaster_pastedeploy#18]
I recently updated from Pyramid-1.7.2 to Pyramid-1.10 and found my app no longer worked. One of my command line scripts uses settings obtained by calling `pyramid.paster.get_appsettings`.

On Pyramid-1.7.2, the returned dictionary(I think an instance of `paste.deploy.AttrDict`) has values of the main section as well as those in the `[DEFAULT]` section. In Pyramid-1.10 (which under the hood uses `plaster` and `plaster_pastedeploy`), the returned object(`ConfigDict`) does not have settings from `[DEFAULT]` section. These settings are stored separately in `global_conf` attribute but trying to use them directly gives a `KeyError`.

Is this intended behaviour - meaning this was broken in older versions (Defaults should never explicitly be part of returned settings) or is this a regression.

As a workaround, my loading code checks if DEFAULT values are part of settings and adds them if this is not the case to maintain compatibility across pyramid versions.

```
def load_settings(inifile, section_name):
    """
    Load the settings from paste ini file
    :param inifile: The full path to the INI file
    :param section_name: Name of the section which has settings.
                         This is passed as name to get_appsettings
    """
    settings = get_appsettings(inifile, name=section_name)
    gc_keys = settings.global_conf.keys()
    skeys = settings.keys()
    # Pyramid>=1.9 uses new plaster which mysteriously does not merge
    # global config into settings dict
    if not set(gc_keys).issubset(set(skeys)):
        settings.update(settings.global_conf)
    return settings
```

**Comment by bertjwregeer** [comment]
`plaster_pastedeploy` uses `pastedeploy` under the hood, but yes, it seems to no longer merge the two automatically.

https://github.com/Pylons/plaster_pastedeploy/blob/master/src/plaster_pastedeploy/__init__.py#L264

Previously, using PasteDeploy directly, `appconfig` would take the `global_conf` and then update the dictionary with `local_conf` thereby overriding the global with the local:

https://github.com/Pylons/pastedeploy/blob/9cbc584a86bd1ae425bd0c0c3c00617d7e59475d/paste/deploy/loadwsgi.py#L718-L723

Your "fix" does not do the same thing, and allows the globals to override the locals, just a heads up.

This does look like a regression when using the `.ini` files using `plaster_pastedeploy`.

**Comment by mmerickel** [comment]
Pastedeploy has specific syntax for pulling in settings from the global. See the `get` syntax in https://github.com/Pylons/plaster_pastedeploy/blob/master/tests/sample_configs/test_settings.ini for example. Considering the signature is also `(global_conf, **settings)` it stands to reason they should generally be kept separate.

Note also that this is only the case for appconfig and is this a huge inconsistency between appconfig and the actual app factory in which appconfig is not returning the same thing passed to the factory in get_app. 

Do we really want to bring back the old behavior here? I think the new one is cleaner and more consistent. I acknowledge that I agree it’s a regression versus using pastedeploy directly but I’m tempted to change pastedeploy in this regard versus reverting plaster_pastedeploy.

**Comment by redbaron4** [comment]
@bertjwregeer Thanks for the heads up. I understand your concern but this "fix" is only concerned with checking whether we are on older Pyramid. It does not need to reconcile global and local settings (any overrides will be taken care of already), just checks whether `get_appsettings` returned `[DEFAULT]` as part of settings or not (older pyramid/pastedeploy behaviour) and adds them if not.

**Comment by bertjwregeer** [comment]
@redbaron4 I understand what you are trying to do, but I am letting you know that since the order of operations is switched you will get different results.

Here is a sample:

```
[DEFAULT]
someval = "This is a global string"

[somesection]
someval = "This is a local string"
localvar = "This is a local var only"
```

In the old code, `settings` as a `dict` would look like this:

```
{
    'someval' = 'This is a local string',
    'localvar' = 'This is a local var only',
}
```

However with your code you will get:

```
{
    'someval' = 'This is a global string',
    'localvar' = 'This is a local var only',
}
```

Due to order of operations. You want the local variables to override the global variables to match the previous behaviour. If you don't have any overlap in keys... then you are more than welcome to ignore this :-).

You'll want to change your code as follows:

```
def load_settings(inifile, section_name):
    """
    Load the settings from paste ini file
    :param inifile: The full path to the INI file
    :param section_name: Name of the section which has settings.
                         This is passed as name to get_appsettings
    """
    settings = get_appsettings(inifile, name=section_name)
    gc_keys = settings.global_conf.keys()
    skeys = settings.keys()
    # Pyramid>=1.9 uses new plaster which mysteriously does not merge
    # global config into settings dict
    if not set(gc_keys).issubset(set(skeys)):
        merged_settings = dict(**settings.global_conf)
        merged_settings.update(settings)  # Local settings override the global ones
        return merged_settings
    return settings
```

**Comment by redbaron4** [comment]
@mmerickel I agree it is cleaner to keep the "global" settings separate and that it would be better to fix `pastedeploy` for consistency.

However, returning a `ConfigDict` containing an attribute like `global_conf` is at odds with the documentation of the `ILoader` interface of plaster

https://github.com/Pylons/plaster/blob/e70e55c182a8300d7ccf67e54d47740c72e72cd8/src/plaster/interfaces.py#L34-L54

which states that return is a plain dictionary.

Maybe the docs for `pyramid.paster.get_appsettings` and `plaster.interface.ILoader` can also be updated?

**Comment by redbaron4** [comment]
@bertjwregeer Thanks for the more complete fix. But as you correctly guessed there is no overlap in keys in this particular app.

**Comment by mmerickel** [comment]
I'd rather not fix this. If you need it in your app you can use the `settings.global_conf` trick. The inconsistency requested here between `get_wsgi_app_settings` and the settings injected into `get_wsgi_app` just does not seem like a good thing to do.

**Comment by redbaron4** [comment]
@mmerickel Fair enough. But I would suggest the documentation (not just here but at `pyramid.paster.get_appsettings` and `plaster.interface.ILoader`) be updated. This would help others who run into the same issue (esp. when migrating apps from older versions of pyramid).

**Comment by mmerickel** [comment]
I'm not sure what I would say in that documentation but I'm willing to review a pull request. Any loader is free to add its own additions to the required api so long as the user of the loader is aware that they are not guaranteed. This is common in any system where you program against an interface - you can always do isinstance checks etc to find out if the api has extra features.
